(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/goods/bd-service"],{"6a95":function(e,t,n){},"6cd2":function(e,t,n){"use strict";n("6a95")},"828d":function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var r=n("2f62");function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter(function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable})),n.push.apply(n,r)}return n}function c(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(n,!0).forEach(function(t){i(e,t,n[t])}):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(n).forEach(function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))})}return e}function i(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}var l={name:"bd-service",props:{name:String,url:String},computed:c({},(0,r.mapState)({mall:function(e){return e.mallConfig.mall}})),methods:{router:function(t){e.navigateTo({url:t})},makePhoneCall:function(){this.mall.setting.contact_tel&&e.makePhoneCall({phoneNumber:this.mall.setting.contact_tel})},navService:function(){1==this.mall.setting.web_service_type?(console.log("=11"),this.router("/pages/web/web?url="+encodeURIComponent(this.mall.setting.web_service_url))):2==this.mall.setting.web_service_type&&(console.log("=22"),wx.openCustomerServiceChat({extInfo:{url:decodeURIComponent(this.mall.setting.web_service_url)},corpId:this.mall.setting.enterprise_wechat_id,success:function(e){console.log(e)},fail:function(e){console.log(e)}}))}}};t.default=l}).call(this,n("543d")["default"])},"861b":function(e,t,n){"use strict";n.r(t);var r=n("d6d6"),o=n("dac6");for(var c in o)"default"!==c&&function(e){n.d(t,e,function(){return o[e]})}(c);n("6cd2");var i=n("2877"),l=Object(i["a"])(o["default"],r["a"],r["b"],!1,null,"0459b8b2",null);t["default"]=l.exports},d6d6:function(e,t,n){"use strict";var r=function(){var e=this,t=e.$createElement;e._self._c},o=[];n.d(t,"a",function(){return r}),n.d(t,"b",function(){return o})},dac6:function(e,t,n){"use strict";n.r(t);var r=n("828d"),o=n.n(r);for(var c in r)"default"!==c&&function(e){n.d(t,e,function(){return r[e]})}(c);t["default"]=o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/goods/bd-service-create-component',
    {
        'components/page-component/goods/bd-service-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("861b"))
        })
    },
    [['components/page-component/goods/bd-service-create-component']]
]);                
