(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-shop/app-shop"],{"400c":function(t,n,e){"use strict";e.r(n);var u=e("ad18"),r=e("dad3");for(var o in r)"default"!==o&&function(t){e.d(n,t,function(){return r[t]})}(o);e("63be");var a=e("2877"),i=Object(a["a"])(r["default"],u["a"],u["b"],!1,null,"f2f31784",null);n["default"]=i.exports},"63be":function(t,n,e){"use strict";e("e92b")},"9abd":function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e={name:"app-shop",props:{list:{type:Array,default:function(){return[]}},navPicUrl:{type:String,default:function(){return""}},scorePicUrl:{type:String,default:function(){return""}},showName:{type:Boolean,default:function(){return!0}},showScore:{type:Boolean,default:function(){return!0}},showTel:{type:Boolean,default:function(){return!0}},scrollTop:{type:Number,default:function(){return 0}},value:{type:Boolean,default:function(){return!0}}},data:function(){return{height:0,request:!0}},created:function(){var n=this;t.getSystemInfo({success:function(t){n.height=t.windowHeight}})},methods:{autoEnd:function(){var t=this;this.$lazyLoadingData("app-shop").then(function(n){n[0].height+n[0].top<t.height&&(t.request=!1,t.$emit("input",t.request))})}},watch:{scrollTop:{handler:function(t,n){t>n&&this.request&&this.autoEnd()}}},computed:{carCount:function(){return function(t){return new Array(t.score)}},newList:function(){return this.list.forEach(function(t){t.score instanceof Array||(t.score=new Array(t.score))}),this.list}}};n.default=e}).call(this,e("543d")["default"])},ad18:function(t,n,e){"use strict";var u=function(){var t=this,n=t.$createElement;t._self._c},r=[];e.d(n,"a",function(){return u}),e.d(n,"b",function(){return r})},dad3:function(t,n,e){"use strict";e.r(n);var u=e("9abd"),r=e.n(u);for(var o in u)"default"!==o&&function(t){e.d(n,t,function(){return u[t]})}(o);n["default"]=r.a},e92b:function(t,n,e){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-shop/app-shop-create-component',
    {
        'components/page-component/app-shop/app-shop-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("400c"))
        })
    },
    [['components/page-component/app-shop/app-shop-create-component']]
]);                
