(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/user-center/components/app-menu"],{"41fc":function(t,e,r){"use strict";r("871f")},4367:function(t,e,r){"use strict";r.r(e);var n=r("b7d0"),a=r("6fd3");for(var i in a)"default"!==i&&function(t){r.d(e,t,function(){return a[t]})}(i);r("41fc");var o=r("2877"),c=Object(o["a"])(a["default"],n["a"],n["b"],!1,null,"3a2be1ce",null);e["default"]=c.exports},"621b":function(t,e,r){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n=r("2f62");function a(t,e){var r=Object.keys(t);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(t);e&&(n=n.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),r.push.apply(r,n)}return r}function i(t){for(var e=1;e<arguments.length;e++){var r=null!=arguments[e]?arguments[e]:{};e%2?a(r,!0).forEach(function(e){o(t,e,r[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(r)):a(r).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(r,e))})}return t}function o(t,e,r){return e in t?Object.defineProperty(t,e,{value:r,enumerable:!0,configurable:!0,writable:!0}):t[e]=r,t}var c={name:"app-menu",props:{value:Object,bg:Object},data:function(){return{height:136,data:{}}},computed:i({},(0,n.mapState)({mall:function(t){return t.mallConfig.mall},userCenterImg:function(t){return t.mallConfig.__wxapp_img.user_center},is_vip_card_user:function(t){return t.user.info&&t.user.info.is_vip_card_user?1:0}}),{},(0,n.mapGetters)({userInfo:"user/info"}),{areaStyle:function(){var t="margin-top: ".concat(this.data.margin,"rpx;");return this.data.show_title&&1==this.data.card&&1==this.data.titleInCard&&(t+="padding-top: 16rpx;"),1==this.data.card&&1==this.data.titleInCard&&(t+="background-color: ".concat(this.data.card_bg,";")),t},listStyle:function(){var t="";return 1==this.data.card&&0==this.data.titleInCard&&(t+="padding: ".concat(this.data.card_margin,"rpx 20rpx;")),t},numberStyle:function(){var t="color: ".concat(this.data.number_color,";font-size: ").concat(this.data.number_size,"rpx;");return 1!=this.data.mode&&(t+="margin-bottom: 12rpx;"),t},titleStyle:function(){var t="color: ".concat(this.data.title_color,";font-size: ").concat(this.data.title_size,"rpx;");return t}}),created:function(){this.data=JSON.parse(JSON.stringify(this.value))},methods:{}};e.default=c},"6fd3":function(t,e,r){"use strict";r.r(e);var n=r("621b"),a=r.n(n);for(var i in n)"default"!==i&&function(t){r.d(e,t,function(){return n[t]})}(i);e["default"]=a.a},"871f":function(t,e,r){},b7d0:function(t,e,r){"use strict";var n=function(){var t=this,e=t.$createElement;t._self._c},a=[];r.d(e,"a",function(){return n}),r.d(e,"b",function(){return a})}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/user-center/components/app-menu-create-component',
    {
        'pages/user-center/components/app-menu-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("4367"))
        })
    },
    [['pages/user-center/components/app-menu-create-component']]
]);                
