(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/basic-component/app-tab-bar/app-tab-bar"],{"1d56":function(t,e,r){"use strict";r.r(e);var n=r("de3c"),a=r("ef0f");for(var o in a)"default"!==o&&function(t){r.d(e,t,function(){return a[t]})}(o);r("6181");var c=r("2877"),u=Object(c["a"])(a["default"],n["a"],n["b"],!1,null,"f0217ace",null);e["default"]=u.exports},6181:function(t,e,r){"use strict";r("f2e1")},c7c6:function(t,e,r){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n=r("2f62");function a(t,e){var r=Object.keys(t);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(t);e&&(n=n.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),r.push.apply(r,n)}return r}function o(t){for(var e=1;e<arguments.length;e++){var r=null!=arguments[e]?arguments[e]:{};e%2?a(r,!0).forEach(function(e){c(t,e,r[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(r)):a(r).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(r,e))})}return t}function c(t,e,r){return e in t?Object.defineProperty(t,e,{value:r,enumerable:!0,configurable:!0,writable:!0}):t[e]=r,t}var u={data:function(){return{router:"",type:1,list:[1,2,3,4,5],indexs:2}},props:{pageCount:Number},computed:o({},(0,n.mapGetters)("mallConfig",{tabBarNavs:"getNavBar"}),{},(0,n.mapGetters)("iPhoneX",{botNavHei:"getNavHei"}),{},(0,n.mapState)("mallConfig",{bottom_background_color:function(t){return t.navbar.bottom_background_color},shadow:function(t){return t.navbar.shadow}})),created:function(){this.router=this.$platDiff.tabBarUrl(null,this.pageCount),1==this.tabBarNavs.is_eject&&(this.type=2,this.indexs=this.tabBarNavs.eject_num-1)},watch:{}};e.default=u},de3c:function(t,e,r){"use strict";var n=function(){var t=this,e=t.$createElement;t._self._c},a=[];r.d(e,"a",function(){return n}),r.d(e,"b",function(){return a})},ef0f:function(t,e,r){"use strict";r.r(e);var n=r("c7c6"),a=r.n(n);for(var o in n)"default"!==o&&function(t){r.d(e,t,function(){return n[t]})}(o);e["default"]=a.a},f2e1:function(t,e,r){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/basic-component/app-tab-bar/app-tab-bar-create-component',
    {
        'components/basic-component/app-tab-bar/app-tab-bar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("1d56"))
        })
    },
    [['components/basic-component/app-tab-bar/app-tab-bar-create-component']]
]);                
