(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-sup-vip/app-sup-vip"],{2558:function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement;t._self._c},u=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return u})},"288e":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=n("2f62");function u(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,r)}return n}function i(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?u(n,!0).forEach(function(e){o(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):u(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function o(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var a={name:"app-sup-vip",props:{discount:{type:String,default:function(){return null}},is_vip_card_user:{type:Number,default:function(){return 0}},margin:{type:String,default:function(){return"0"}}},data:function(){return{is_show:!1}},created:function(){var t=this;1==t.is_vip_card_user?"1"==t.mall.setting.is_show_super_vip?t.is_show=!0:t.is_show=!1:"1"==t.mall.setting.is_show_normal_vip?t.is_show=!0:t.is_show=!1},computed:i({},(0,r.mapState)({mall:function(t){return t.mallConfig.mall},userInfo:function(t){return t.user.info}}))};e.default=a},"348c":function(t,e,n){"use strict";n.r(e);var r=n("2558"),u=n("43ea");for(var i in u)"default"!==i&&function(t){n.d(e,t,function(){return u[t]})}(i);n("d240");var o=n("2877"),a=Object(o["a"])(u["default"],r["a"],r["b"],!1,null,"0fdf0372",null);e["default"]=a.exports},"43ea":function(t,e,n){"use strict";n.r(e);var r=n("288e"),u=n.n(r);for(var i in r)"default"!==i&&function(t){n.d(e,t,function(){return r[t]})}(i);e["default"]=u.a},7213:function(t,e,n){},d240:function(t,e,n){"use strict";n("7213")}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-sup-vip/app-sup-vip-create-component',
    {
        'components/page-component/app-sup-vip/app-sup-vip-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("348c"))
        })
    },
    [['components/page-component/app-sup-vip/app-sup-vip-create-component']]
]);                
