(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["plugins/bargain/common-buttom"],{"22e0":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=n("2f62");function o(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,r)}return n}function i(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?o(n,!0).forEach(function(e){u(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):o(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function u(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var c=function(){return n.e("components/basic-component/app-iphone-x/app-iphone-x").then(n.bind(null,"7598"))},a=function(){return n.e("components/basic-component/app-empty-bottom/app-empty-bottom").then(n.bind(null,"0c06"))},p={name:"common-buttom",components:{appEmptyBottom:a,appIphoneX:c},computed:i({},(0,r.mapState)("gConfig",{iphone:function(t){return t.iphone},iphoneHeight:function(t){return t.iphoneHeight}})),props:{status:{type:String,default:"index"},theme:Object},data:function(){return{}},methods:{nav1:function(){t.redirectTo({url:"/plugins/bargain/index/index"})},nav2:function(){t.redirectTo({url:"/plugins/bargain/order-list/order-list"})}}};e.default=p}).call(this,n("543d")["default"])},"2faf":function(t,e,n){"use strict";n.r(e);var r=n("c65d"),o=n("91a1");for(var i in o)"default"!==i&&function(t){n.d(e,t,function(){return o[t]})}(i);n("d9df");var u=n("2877"),c=Object(u["a"])(o["default"],r["a"],r["b"],!1,null,"649371cc",null);e["default"]=c.exports},"8e6b":function(t,e,n){},"91a1":function(t,e,n){"use strict";n.r(e);var r=n("22e0"),o=n.n(r);for(var i in r)"default"!==i&&function(t){n.d(e,t,function(){return r[t]})}(i);e["default"]=o.a},c65d:function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement,n=(t._self._c,Number(96));t.$mp.data=Object.assign({},{$root:{m0:n}})},o=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return o})},d9df:function(t,e,n){"use strict";n("8e6b")}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'plugins/bargain/common-buttom-create-component',
    {
        'plugins/bargain/common-buttom-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("2faf"))
        })
    },
    [['plugins/bargain/common-buttom-create-component']]
]);                
